server:
  error:
    include-stacktrace: never

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dockert2s?useSSL=false&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
    username: root
    password: secret
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    defer-datasource-initialization: true
    generate-ddl: true
    hibernate:
      ddl-auto: update

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  sql:
    init:
      mode: always # Spring Boot >=v2.5.0


logging:
  level:
    org:
      hibernate:
        SQL: DEBUG

api:
  security:
    token:
      secret: ${JWT_SECRET:my-secret-t2s}
