server:
  error:
    include-stacktrace: never

spring:
  datasource:
    url: ${URL_CONEXAO_BANCO_PROD}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: ${DRIVER_CLASS_NAME}

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  sql:
    init:
      mode: always # Spring Boot >=v2.5.0

  application:
    name: dockert2s

management:
  endpoints:
    web:
      exposure:
        include: info,health,metrics,prometheus

info:
  app: DockerT2S - API de Gerenciamento de Conteineres
  github: https://github.com/hiranneri/dockert2s

api:
  security:
    token:
      secret: ${JWT_SECRET}
