version: '3.8'
x-database-variables: &database-variables
  SPRING_DATASOURCE_URL: ${URL_CONEXAO_BANCO_PROD}
  SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
  SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
  SPRING_DATASOURCE_DRIVER_CLASS_NAME: ${DRIVER_CLASS_NAME}
  SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect

services:
  banco:
    image: postgres:15.4-alpine
    container_name: dockert2s-pg
    ports:
      - "5432:5432"
    volumes:
      - "dockert2s-pg-volume:/var/lib/postgresql/data"
    environment:
      <<: *database-variables
    networks:
      - dockert2s-network
  prometheus:
    image: prom/prometheus:latest
    container_name: dockert2s-prometheus
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    container_name: dockert2s-grafana
    ports:
      - "3000:3000"

  dockert2s:
    image: hiranneri/dockert2s:latest
    container_name: dockert2s
    ports:
      - "8080:8080"
    environment:
      <<: *database-variables
    networks:
      - dockert2s-network
    depends_on: [banco]
    deploy:
      resources:
        limits:
          memory: 500M
        reservations:
          memory: 500M

networks:
  dockert2s-network:
    driver: bridge

volumes:
  dockert2s-mysql-volume: