version: '3.8'
x-database-variables: &database-variables
  SPRING_DATASOURCE_URL: ${URL_CONEXAO_BANCO_PROD}
  SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
  SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
  SPRING_DATASOURCE_DRIVER_CLASS_NAME: ${DRIVER_CLASS_NAME}
  SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: dockert2s-prometheus
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"
    depends_on: [dockert2s]

  grafana:
    image: grafana/grafana:latest
    container_name: dockert2s-grafana
    ports:
      - "3000:3000"
    depends_on: [dockert2s]

  dockert2s:
    image: hiranneri/dockert2s:latest
    container_name: dockert2s
    ports:
      - "80:8080"
    environment:
      <<: *database-variables
    networks:
      - dockert2s-network
    deploy:
      resources:
        limits:
          memory: 500M
        reservations:
          memory: 500M

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 180 --services dockert2s

networks:
  dockert2s-network:
    driver: bridge

volumes:
  dockert2s-pg-volume: